package com.dessalines.thumbkey.utils

import com.dessalines.thumbkey.keyboards.KB_BG_PHONETIC_MESSAGEASE_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_BG_THUMBKEY_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_BY_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_BY_THUMBKEY_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_CA_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_DA_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_DE_MESSAGEEASE
import com.dessalines.thumbkey.keyboards.KB_DE_MESSAGEEASE_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_DE_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_DE_THUMBKEY_MULTILINGUAL
import com.dessalines.thumbkey.keyboards.KB_DE_TYPESPLIT
import com.dessalines.thumbkey.keyboards.KB_ENEO_MESSAGEEASE_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_EN_CZ_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_EN_DA_THUMBKEY_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_EN_DOUBLE_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_EN_EE_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_EN_FR_MESSAGEASE_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_EN_IT_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_EN_MESSAGEEASE
import com.dessalines.thumbkey.keyboards.KB_EN_MESSAGEEASE_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_EN_MI_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_EN_MI_THUMBKEY_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_EN_NO_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_EN_NO_TYPESPLIT
import com.dessalines.thumbkey.keyboards.KB_EN_PL_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_EN_QWERTYFOUR
import com.dessalines.thumbkey.keyboards.KB_EN_SK_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_EN_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_EN_THUMBKEY_COMPOSE
import com.dessalines.thumbkey.keyboards.KB_EN_THUMBKEY_PROGRAMMER
import com.dessalines.thumbkey.keyboards.KB_EN_THUMBKEY_PROGRAMMER_WIDE
import com.dessalines.thumbkey.keyboards.KB_EN_THUMBKEY_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_EN_TWO_HANDS
import com.dessalines.thumbkey.keyboards.KB_EN_TWO_HANDS_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_EN_TWO_HANDS_SYMBOLS_NUMBERS
import com.dessalines.thumbkey.keyboards.KB_EN_TYPESPLIT
import com.dessalines.thumbkey.keyboards.KB_EOENDE_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_ES_CA_MESSAGEEASE
import com.dessalines.thumbkey.keyboards.KB_ES_CA_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_ES_EO_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_ES_MESSAGEEASE
import com.dessalines.thumbkey.keyboards.KB_ES_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_ES_TYPESPLIT
import com.dessalines.thumbkey.keyboards.KB_EU_ES_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_EU_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_FA_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_FI_EE_MESSAGEEASE_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_FI_MESSAGEEASE
import com.dessalines.thumbkey.keyboards.KB_FI_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_FI_THUMBKEY_WIDE
import com.dessalines.thumbkey.keyboards.KB_FI_TYPESPLIT
import com.dessalines.thumbkey.keyboards.KB_FR_MESSAGEEASE
import com.dessalines.thumbkey.keyboards.KB_FR_THUMBKEY_V1
import com.dessalines.thumbkey.keyboards.KB_FR_THUMBKEY_V2
import com.dessalines.thumbkey.keyboards.KB_FR_TYPESPLIT
import com.dessalines.thumbkey.keyboards.KB_GR_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_HE_MESSAGEEASE
import com.dessalines.thumbkey.keyboards.KB_HE_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_HR_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_HR_THUMBKEY_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_HR_TWO_HANDS
import com.dessalines.thumbkey.keyboards.KB_HU_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_ID_THUMBKEY_SYMBOLS_NUMERIC_V1
import com.dessalines.thumbkey.keyboards.KB_ID_THUMBKEY_SYMBOLS_V1
import com.dessalines.thumbkey.keyboards.KB_ID_THUMBKEY_SYMBOLS_V2
import com.dessalines.thumbkey.keyboards.KB_IT_MESSAGEEASE
import com.dessalines.thumbkey.keyboards.KB_IT_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_IT_TYPESPLIT
import com.dessalines.thumbkey.keyboards.KB_JA_THUMBKEY_HIRAGANA
import com.dessalines.thumbkey.keyboards.KB_JA_THUMBKEY_KATAKANA
import com.dessalines.thumbkey.keyboards.KB_JA_TYPESPLIT_HIRAGANA
import com.dessalines.thumbkey.keyboards.KB_JA_TYPESPLIT_KATAKANA
import com.dessalines.thumbkey.keyboards.KB_KA_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_KZ_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_LT_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_LV_LTG_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_MATH_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_NL_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_NO_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_PL_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_PL_TYPESPLIT
import com.dessalines.thumbkey.keyboards.KB_PT_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_PT_TYPESPLIT
import com.dessalines.thumbkey.keyboards.KB_RU_MESSAGEEASE
import com.dessalines.thumbkey.keyboards.KB_RU_MESSAGEEASE_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_RU_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_RU_THUMBKEY_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_SK_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_SV_MESSAGEEASE
import com.dessalines.thumbkey.keyboards.KB_SV_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_T9
import com.dessalines.thumbkey.keyboards.KB_TR_THUMBKEY
import com.dessalines.thumbkey.keyboards.KB_UK_MESSAGEEASE_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_UK_RU_MESSAGEEASE_SYMBOLS
import com.dessalines.thumbkey.keyboards.KB_UK_THUMBKEY

// Make sure new keyboards have a new index, even if they are in the middle
// Keyboards are placed in alphabetical order
enum class KeyboardLayout(val index: Int, val keyboardDefinition: KeyboardDefinition) {
    ENThumbKey(0, KB_EN_THUMBKEY),
    ENThumbKeyProgrammer(1, KB_EN_THUMBKEY_PROGRAMMER),
    DEThumbKey(2, KB_DE_THUMBKEY),
    DAThumbKey(3, KB_DA_THUMBKEY),
    ESThumbKey(4, KB_ES_THUMBKEY),
    EUThumbKey(5, KB_EU_THUMBKEY),
    FAThumbKey(6, KB_FA_THUMBKEY),
    FIThumbKey(7, KB_FI_THUMBKEY),
    FRThumbKeyV1(8, KB_FR_THUMBKEY_V1),
    ITThumbKey(9, KB_IT_THUMBKEY),
    NLThumbKey(10, KB_NL_THUMBKEY),
    PLThumbKey(11, KB_PL_THUMBKEY),
    PTThumbKey(12, KB_PT_THUMBKEY),
    RUThumbKey(13, KB_RU_THUMBKEY),
    UKThumbKey(14, KB_UK_THUMBKEY),
    ENMessageEase(15, KB_EN_MESSAGEEASE),
    ENMessageEaseSymbols(16, KB_EN_MESSAGEEASE_SYMBOLS),
    HEMessageEase(17, KB_HE_MESSAGEEASE),
    RUThumbKeySymbols(18, KB_RU_THUMBKEY_SYMBOLS),
    BYThumbKey(19, KB_BY_THUMBKEY),
    BYThumbKeySymbols(20, KB_BY_THUMBKEY_SYMBOLS),
    ENThumbKeySymbols(21, KB_EN_THUMBKEY_SYMBOLS),
    FIThumbKeyWide(22, KB_FI_THUMBKEY_WIDE),
    DEMessageEase(23, KB_DE_MESSAGEEASE),
    NOThumbKey(24, KB_NO_THUMBKEY),
    DEThumbKeyMultiLingual(25, KB_DE_THUMBKEY_MULTILINGUAL),
    KAThumbKey(26, KB_KA_THUMBKEY),
    IDThumbKeySymbolsV1(27, KB_ID_THUMBKEY_SYMBOLS_V1),
    FRMessageEase(28, KB_FR_MESSAGEEASE),
    RUMessageEaseSymbols(29, KB_RU_MESSAGEEASE_SYMBOLS),
    T9(30, KB_T9),
    JAThumbKeyHiragana(31, KB_JA_THUMBKEY_HIRAGANA),
    JAThumbKeyKatakana(32, KB_JA_THUMBKEY_KATAKANA),
    FRThumbKeyV2(33, KB_FR_THUMBKEY_V2),
    SVThumbKey(34, KB_SV_THUMBKEY),
    TRThumbKey(35, KB_TR_THUMBKEY),
    ENTypeSplit(36, KB_EN_TYPESPLIT),
    ESTypeSplit(37, KB_ES_TYPESPLIT),
    DETypeSplit(38, KB_DE_TYPESPLIT),
    FRTypeSplit(39, KB_FR_TYPESPLIT),
    ITTypeSplit(40, KB_IT_TYPESPLIT),
    PTTypeSplit(41, KB_PT_TYPESPLIT),
    PLTypeSplit(42, KB_PL_TYPESPLIT),
    ENTwoHands(43, KB_EN_TWO_HANDS),
    ENThumbKeyProgrammerWide(44, KB_EN_THUMBKEY_PROGRAMMER_WIDE),
    HUThumbKey(45, KB_HU_THUMBKEY),
    ESEOThumbKey(46, KB_ES_EO_THUMBKEY),
    ITMessageEase(47, KB_IT_MESSAGEEASE),
    ENSKThumbKey(48, KB_EN_SK_THUMBKEY),
    HEThumbKey(49, KB_HE_THUMBKEY),
    EOENDEThumbKey(50, KB_EOENDE_THUMBKEY),
    GRThumbKey(51, KB_GR_THUMBKEY),
    ENCZThumbKey(52, KB_EN_CZ_THUMBKEY),
    ESMessageEase(53, KB_ES_MESSAGEEASE),
    RUMessageEase(54, KB_RU_MESSAGEEASE),
    BGThumbKeySymbols(55, KB_BG_THUMBKEY_SYMBOLS),
    HRTwoHands(56, KB_HR_TWO_HANDS),
    HRThumbKey(57, KB_HR_THUMBKEY),
    HRThumbKeySymbols(58, KB_HR_THUMBKEY_SYMBOLS),
    FITypeSplit(59, KB_FI_TYPESPLIT),
    LVLTGThumbKey(60, KB_LV_LTG_THUMBKEY),
    LTThumbKey(61, KB_LT_THUMBKEY),
    IDThumbKeySymbolsV2(62, KB_ID_THUMBKEY_SYMBOLS_V2),
    IDThumbKeySymbolsNumeric(63, KB_ID_THUMBKEY_SYMBOLS_NUMERIC_V1),
    ESCAThumbKey(64, KB_ES_CA_THUMBKEY),
    ENITThumbKey(65, KB_EN_IT_THUMBKEY),
    ENEOMessageEaseSymbols(66, KB_ENEO_MESSAGEEASE_SYMBOLS),
    UKRUMessageEaseSymbols(67, KB_UK_RU_MESSAGEEASE_SYMBOLS),
    DEMessageEaseSymbols(68, KB_DE_MESSAGEEASE_SYMBOLS),
    CAThumbKey(69, KB_CA_THUMBKEY),
    MATHThumbKey(70, KB_MATH_THUMBKEY),
    ENEEThumbKey(71, KB_EN_EE_THUMBKEY),
    SKThumbKey(72, KB_SK_THUMBKEY),
    ENNOTypeSplit(73, KB_EN_NO_TYPESPLIT),
    ENThumbKeyCompose(74, KB_EN_THUMBKEY_COMPOSE),
    ENNOThumbKey(75, KB_EN_NO_THUMBKEY),
    ENTwoHandsSymbols(76, KB_EN_TWO_HANDS_SYMBOLS),
    ENTwoHandsSymbolsNumbers(77, KB_EN_TWO_HANDS_SYMBOLS_NUMBERS),
    JATypeSplitHiragana(78, KB_JA_TYPESPLIT_HIRAGANA),
    JATypeSplitKatakana(79, KB_JA_TYPESPLIT_KATAKANA),
    EUESThumbKey(80, KB_EU_ES_THUMBKEY),
    ENQwertyFour(81, KB_EN_QWERTYFOUR),
    KZThumbKey(82, KB_KZ_THUMBKEY),
    ENMIThumbKey(83, KB_EN_MI_THUMBKEY),
    ENMIThumbKeySymbols(84, KB_EN_MI_THUMBKEY_SYMBOLS),
    ESCAMessageEase(85, KB_ES_CA_MESSAGEEASE),
    SVMessageEase(86, KB_SV_MESSAGEEASE),
    ENDoubleSymbols(87, KB_EN_DOUBLE_SYMBOLS),
    FIMessageEase(88, KB_FI_MESSAGEEASE),
    ENDAThumbKeySymbols(89, KB_EN_DA_THUMBKEY_SYMBOLS),
    FIEEMessageEase(90, KB_FI_EE_MESSAGEEASE_SYMBOLS),
    ENPLThumbkey(91, KB_EN_PL_THUMBKEY),
    BGPhoneticMessagEaseSymbols(92, KB_BG_PHONETIC_MESSAGEASE_SYMBOLS),
    UKMessageEaseSymbols(93, KB_UK_MESSAGEEASE_SYMBOLS),
    ENFRMessagEaseSymbols(94, KB_EN_FR_MESSAGEASE_SYMBOLS),
}
