steps:
  prettier_markdown_check:
    image: tmknom/prettier
    commands:
      - prettier -c "**/*.md" "**/*.yml"

  check_formatting:
    image: cimg/android:2023.09.1
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew lintKotlin
    environment:
      GRADLE_USER_HOME: ".gradle"

  build_project:
    image: cimg/android:2023.09.1
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew assembleDebug
    environment:
      GRADLE_USER_HOME: ".gradle"

  notify:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'Thumb-Key build ${CI_PIPELINE_STATUS}: ${CI_PIPELINE_URL}' ntfy.sh/thumbkey_ci"
    when:
      status: [failure, success]
