variables:
  - &slow_check_paths
    - path:
        - "**/*.kt"
        - "**/*.gradle"
        - ".woodpecker.yml"

steps:
  check_formatting:
    image: cimg/android:2023.05
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew lintKotlin
    when: *slow_check_paths

  prettier_markdown_check:
    image: tmknom/prettier
    commands:
      - prettier -c "*.md" "*.yml"

  build_project:
    image: cimg/android:2023.05
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew assembleDebug
    when: *slow_check_paths

  notify:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'Thumb-Key build ${CI_PIPELINE_STATUS}: ${CI_PIPELINE_URL}' ntfy.sh/thumbkey_ci"
    when:
      status: [failure, success]
