name: ðŸž Issue report
description: Report an issue or bug
labels: [bug]
body:
- type: textarea
  id: reproduce-steps
  attributes:
    label: Steps to reproduce
    description: Provide an example of the issue.
    placeholder: |
      Example:
        1. First step
        2. Second step
        3. Issue here
  validations:
    required: true

- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    description: Explain what you should expect to happen.
    placeholder: |
      Example:
        "This should happen..."
  validations:
    required: true

- type: textarea
  id: actual-behavior
  attributes:
    label: Actual behavior
    description: Explain what actually happens.
    placeholder: |
      Example:
        "This happened instead..."
  validations:
    required: true

- type: input
  id: version
  attributes:
    label: version of the program
    placeholder: >-
      Example: "2.6.14"
  validations:
    required: true

- type: input
  id: android-version
  attributes:
    label: Android version
    description: You can find this somewhere in your Android settings.
    placeholder: |
      Example: "Android 14"
  validations:
    required: true

- type: input
  id: device
  attributes:
    label: Device
    description: List your device and model.
    placeholder: |
      Example: "Google Pixel 8"
  validations:
    required: true

- type: textarea
  id: other-details
  attributes:
    label: Other details
    placeholder: Additional details and attachments.

- type: checkboxes
  id: acknowledgements
  attributes:
    label: Acknowledgements
    description: >-
      Read this carefully, I will close and ignore your issue if you skimmed through this.
    options:
    - label: I have written a short but informative title.
      required: true
    - label: I have updated the app to **[the latest version](https://github.com/user/repo/releases/latest)**.
      required: true
    - label: >-
        I have searched the existing issues and this is a new one, **NOT** a 
        duplicate or related to another open issue.
      required: true
    - label: >-
        This is not a question or a discussion, in which case I should have 
        gone to [lemmy.ml/c/thumbkey](https://lemmy.ml/c/thumbkey)
      required: true
    - label: >-
        This is a **single** bug report, in case of multiple bugs I will open 
        a separate issue for each one 
        (they can always link to each other if related)
      required: true
    - label: I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. ðŸ¤¡
    - label: I have filled out all of the requested information in this form.
      required: true
